# Generated by Django 3.2.9 on 2021-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citycount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('cases', models.IntegerField()),
            ],
            options={
                'db_table': 'CityCount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countrycount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('cases', models.IntegerField()),
            ],
            options={
                'db_table': 'CountryCount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peopledetail',
            fields=[
                ('people_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=31, null=True)),
                ('last_name', models.CharField(blank=True, max_length=31, null=True)),
                ('has_covid', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'PeopleDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincecount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('cases', models.IntegerField()),
            ],
            options={
                'db_table': 'ProvinceCount',
                'managed': False,
            },
        ),
    ]
